// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwyqvtbhyvegytxyyqow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3eXF2dGJoeXZlZ3l0eHl5cW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjA5OTEsImV4cCI6MjA2ODc5Njk5MX0.kKR8UVRlEi8plOLEjaUHm1_L4Ip2n852LNVnn_ldyGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});