// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdbqoixtsstzcgsubgea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkYnFvaXh0c3N0emNnc3ViZ2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDczNTcsImV4cCI6MjA3MDgyMzM1N30.V4JsBytehZM9EBBTRlu6YCAr7mtNJvs6huxW19p3bXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});